- apps/protocol/src/app/pages/Pools/Detail/PoolOverview.tsx
- apps/protocol/src/app/pages/Save/PolygonSave.tsx
- libs/hooks/src/lib/createStakingRewardsContext.ts
- Restores commits lost in transition:
- Restores calculator
- Fixes formatting on Polygon balance
> Restore dropped commits

- apps/protocol/src/index.html
- package.json
- webpack-config.js
- workspace.json
Ensure static content is sourced with relative paths so that IPFS gateways serve the app properly
> Ensure static content is sourced with relative paths

- workspace.json
- Ensure that the build options necessary for IPFS gateways are only used in production
> Fix local nx workspace config

- apps/protocol/src/app/hooks/useSelectedMassetPrice.ts
- libs/base/src/lib/components/wallet/TransactionGasProvider.tsx
- libs/base/src/lib/context/NetworkProvider.tsx
- Use the correct mAsset price
- Round gas prices from the Matic gas station (breaks estimation otherwise)
> Fix Polygon save deposits

- apps/protocol/src/app/index.tsx
- apps/protocol/src/app/pages/Exchange/index.tsx
- apps/protocol/src/app/pages/Pools/cards/AssetCard.tsx
- apps/protocol/src/app/pages/Pools/cards/Card.tsx
- apps/protocol/src/app/pages/Pools/index.tsx
- apps/protocol/src/app/pages/Save/v2/SaveEthereumOverview.tsx
- Change swap title & url
- Change Pool card appearance
> Change swap title

- apps/protocol/src/app/pages/Pools/Detail/PoolOverview.tsx
> Fix displaying overview 

- apps/protocol/src/app/context/RewardStreamsProvider.tsx
- apps/protocol/src/app/pages/Pools/Detail/ClaimGraph.tsx
- apps/protocol/src/app/pages/Pools/Detail/UserRewards.tsx
- apps/protocol/src/app/pages/Pools/constants.ts
- apps/protocol/src/app/pages/Save/v2/SaveOverview.tsx
- Fixes bug where rewards view doesn't show if user has 0 balance & vested rewards.
> Fix vested rewards in chart

- apps/governance/src/app/components/GovernancePageHeader.tsx
- apps/governance/src/app/index.tsx
- apps/governance/src/app/pages/NotFound.tsx
- apps/governance/src/app/pages/Quests.tsx
- apps/governance/src/app/pages/Stake.tsx
- apps/governance/src/app/pages/Stats.tsx
- apps/governance/src/app/pages/Vote.tsx
- apps/governance/src/app/pages/foo.tsx
- apps/governance/src/app/pages/index.tsx
- apps/protocol/src/app/pages/Exchange/index.tsx
- libs/base/src/lib/components/layout/Navigation.tsx
- Add governance routes
- Adjust active route matching for governance (without mAsset name in path)
> Governance routes

- apps/governance/src/app/pages/Stake/ClaimForm.tsx
- apps/governance/src/app/pages/Stake/StakeBalances.tsx
- apps/governance/src/app/pages/Stake/StakeForm.tsx
- apps/governance/src/app/pages/Stake/StakeForms.tsx
- libs/artifacts/src/graphql/feeders.tsx
- libs/artifacts/src/graphql/feeders/schema.graphql
- libs/artifacts/src/graphql/staking.tsx
- libs/artifacts/src/graphql/staking/apollo-helpers.ts
- libs/artifacts/src/graphql/staking/client.graphql
- libs/artifacts/src/graphql/staking/query.graphql
- libs/artifacts/src/graphql/staking/schema.graphql
- libs/base/src/lib/context/apolloCaches/staking.ts
- libs/base/src/lib/context/apolloCaches/utils.ts
- libs/base/src/lib/theme.ts
- libs/components/src/lib/core/TabsOfTruth.tsx
- Change the queries to naively select the first stakedToken
- Fix some colours in night mode
> Support multiple staked tokens

- apps/governance/src/app/components/GovernancePageHeader.tsx
- apps/governance/src/app/components/StakedTokenSwitcher.tsx
- apps/governance/src/app/context/StakedTokenProvider.tsx
- apps/governance/src/app/context/StakingProvider.tsx
- apps/governance/src/app/pages/Stake/ClaimForm.tsx
- apps/governance/src/app/pages/Stake/StakeBalances.tsx
- apps/governance/src/app/pages/Stake/StakeForm.tsx
- apps/governance/src/app/pages/Stake/index.tsx
- apps/governance/src/main.tsx
- libs/artifacts/src/graphql/staking.tsx
- libs/artifacts/src/graphql/staking/query.graphql
- libs/hooks/src/lib/useBlockPollingSubscription.ts
- Add a component to switch the selected staked token
- Add StakedTokenSwitcher to gov header (Staking page)
- Use the selected StakedToken in staking forms/balances
- Add a query for a particular StakedToken
- Retain Staking query; get all StakedTokens and quests
- Add a provider to select a StakedToken and query it
> Staked token selector

- apps/governance/src/app/context/StakedTokenProvider.tsx
- apps/governance/src/app/pages/Quests/ClaimButtons.tsx
- apps/governance/src/app/pages/Quests/Meta8Logic.tsx
- apps/governance/src/app/pages/Quests/QuestCard.tsx
- apps/governance/src/app/pages/Quests/QuestInfo.tsx
- apps/governance/src/app/pages/Quests/QuestProgress.tsx
- apps/governance/src/app/pages/Quests/QueueOptInOutButtons.tsx
- apps/governance/src/app/pages/Stake/StakeBalances.tsx
- apps/governance/src/app/pages/Vote/DelegateeToggle.tsx
- apps/governance/src/app/pages/Vote/index.tsx
- libs/artifacts/src/graphql/questbook.tsx
- libs/artifacts/src/graphql/questbook/query.graphql
- libs/artifacts/src/graphql/staking.tsx
- libs/artifacts/src/graphql/staking/apollo-helpers.ts
- libs/artifacts/src/graphql/staking/client.graphql
- libs/artifacts/src/graphql/staking/query.graphql
- libs/base/src/lib/context/apolloCaches/staking.ts
- Add opt-in/out of quest completion
- Tweak quest style
- Show permanent/season on quest card
- Move quest description from quest card to objectives
- Add quest time remaining
> More quests

- apps/governance/src/app/pages/Stake/ClaimForm.tsx
- apps/governance/src/app/pages/Stake/StakeBalances.tsx
- apps/governance/src/app/pages/Stake/StakeForms.tsx
- apps/governance/src/app/pages/Stake/context.ts
- apps/governance/src/app/pages/Stake/createRewardsEarnedContext.ts
- apps/governance/src/app/pages/Stake/index.tsx
- libs/artifacts/codegen.yml
- libs/artifacts/src/graphql/.graphqlconfig
- libs/artifacts/src/graphql/staking.tsx
- libs/artifacts/src/graphql/staking/apollo-helpers.ts
- libs/artifacts/src/graphql/staking/client.graphql
- libs/artifacts/src/graphql/staking/query.graphql
- libs/artifacts/src/graphql/staking/schema.graphql
- libs/base/src/lib/context/apolloCaches/staking.ts
- Add staking rewards APY, boosted APY and rewards earned
> Staking rewards earned/APY

- apps/governance/src/app/context/DelegateeListsProvider.tsx
- apps/governance/src/app/pages/Vote/Delegatee.tsx
- apps/governance/src/app/pages/Vote/Leaderboard.tsx
- apps/governance/src/app/pages/Vote/LeaderboardPage.tsx
- libs/artifacts/src/graphql/staking.tsx
- libs/artifacts/src/graphql/staking/apollo-helpers.ts
- libs/artifacts/src/graphql/staking/client.graphql
- libs/artifacts/src/graphql/staking/query.graphql
- libs/artifacts/src/graphql/staking/schema.graphql
- libs/base/src/lib/context/apolloCaches/staking.ts
- Show delegatees in leaderboard before they've staked
- Calculate stkMTA total and share properly
- Update official delegatees list
-  Scroll back to top of pages for leaderboard and profiles
> Delegatees empty state/stkMTA balances

- apps/governance/src/app/components/DelegateSelection.tsx
- apps/governance/src/app/components/GovernancePageHeader.tsx
- apps/governance/src/app/hooks/useDelegationModal.tsx
- apps/governance/src/app/pages/Stake/StakeForm.tsx
- Fix allowance check for stake form
- Adjust delegation modal for overflow-y
- Fix delegation profile style and images
> Fix Delegation UI

- apps/protocol/src/app/components/rewards/BoostCalculator.tsx
- apps/protocol/src/app/hooks/useFeederPoolApy.ts
- apps/protocol/src/app/pages/Pools/Detail/EthereumPool.tsx
- libs/base/src/lib/context/NetworkProvider.tsx
- libs/components/src/lib/core/TransitionCard.tsx
- libs/hooks/src/lib/useCalculateUserBoost.ts
- libs/hooks/src/lib/useVMTABalance.ts
- libs/quick-maths/src/lib/boost.ts
> Updated boost

- apps/governance/src/app/hooks/useDelegatorModal.tsx
- Test PR to check deployment config
> Test deployment

- apps/protocol/src/app/pages/Pools/Detail/Frax/FraxStake.tsx
- apps/protocol/src/app/pages/Save/v2/SaveStake.tsx
- Ensure useBigDecimalInput is called with BigDecimals when available, to avoid unwanted rounding with simple numbers
> Fix useBigDecimalInput rounding

- libs/masset-provider/src/lib/MassetProvider.tsx
> Revert masset change

- apps/protocol/src/app/components/rewards/UserBoost.tsx
- Removes base + max apy
- Adds rewards apy range
> [protocol] Rewards APY tweak

- libs/base/src/lib/context/ApolloProvider.tsx
- libs/data-provider/src/lib/transformRawData.ts
Sidefix: more forgiving timeouts (will only error after 30s without a graphql response)
> Fix: tBTC label

- libs/base/src/lib/components/layout/AppBar.tsx
- libs/base/src/lib/components/layout/GraphWarning.tsx
- libs/base/src/lib/components/layout/Layout.tsx
- Add warning at the top of the page to link to current Graph issues – only on Polygon
> Add data sync warning on polygon

- libs/base/src/lib/components/layout/SettingsButton.tsx
- libs/base/src/lib/context/AccountProvider.tsx
- libs/dumb-components/src/lib/CountUp.tsx
- libs/theme/src/lib/ThemeProvider.tsx
- Fix theme persistence
- Fix 'state reset' effect on mStable logo click
- New T&C url added
> Fix regressions

- apps/governance/src/app/hooks/useBPTBalApy.ts
- apps/governance/src/app/pages/Stake/StakeBalances.tsx
- libs/base/src/lib/context/apolloCaches/index.ts
> Add BAL APY

- libs/base/src/lib/components/layout/AppBar.tsx
- libs/base/src/lib/components/layout/SettingsButton.tsx
- Show network switcher on mobile to switch to polygon, etc
> Show network switcher on mobile

- apps/protocol/src/app/pages/Pools/Detail/PoolOverview.tsx
- libs/base/src/lib/components/layout/GraphWarning.tsx
> Fix/small UI fixes

- apps/protocol/src/app/pages/Pools/Detail/PoolOverview.tsx
- Show user rewards when users have unlocked + withdrawn their balance
> fix: Show user rewards

- libs/base/src/lib/context/NetworkProvider.tsx
- Enables the claiming of BAL for stkBPT stakers that earned it
- Add the `merkleDrop` GraphQL endpoint for mainnet
- Add the `MerkleDropMBPTBAL` address for mainnet
| Verify |
| ------ |
| <img src="https://user-images.githubusercontent.com/5450382/142262103-58d6fce7-c6c1-4a87-8dc5-d290deba320f.png" width="320" /> |
| Claim |
| ------ |
| <img src="https://user-images.githubusercontent.com/5450382/142262268-f009b97c-58fe-42a9-a10b-14fa7eb143ae.png" width="320" /> |
**Testing**
- The rewards for tranche 1 are [available here](https://cloudflare-ipfs.com/ipfs/QmNNqnZMuYzkXpfjbMk1G1WgjuxLGsYBdXvkpDXbeQ4mEV)
> stkBPT Merkle Drops

- libs/base/src/lib/components/layout/MessageHandler.tsx
> [staking] Add affiliate link

- apps/governance/src/app/pages/Stake/ClaimForm.tsx
- apps/governance/src/app/pages/Stake/WithdrawForm.tsx
- Hide platform rewards on MTA
- Fix learn more links
> fix: Dead links on staking

- apps/protocol/src/app/context/RewardStreamsProvider.tsx
- Get the unclaimed rewards from the vault contract to use as the claim range
> Fix claiming earlier ranges

- apps/governance/src/app/pages/Dials/ActiveDial.tsx
- apps/governance/src/app/pages/Dials/DialPreferencesTable.tsx
- apps/governance/src/app/pages/Dials/DialTable.tsx
- apps/governance/src/app/pages/Dials/DialTitle.tsx
- apps/governance/src/app/pages/Dials/DialsSubmit.tsx
- apps/governance/src/app/pages/Dials/EpochDetails.tsx
- apps/governance/src/app/pages/Dials/constants.ts
- apps/governance/src/app/pages/Dials/context/UserDialsContext.tsx
- libs/dumb-components/src/lib/Table.tsx
- Enforce limit of 16 dials per tx
- Handle zero slider reset
- Change epoch date formatting
- Allow event propagation on table row & link to user
- Highlight 100% dial voters 
- Add copy for 10% system revenue
> fix: Misc changes to dials

- apps/governance/src/app/pages/Stake/StakeBalances.tsx
- libs/artifacts/src/graphql/staking.tsx
- libs/artifacts/src/graphql/staking/query.graphql
- Use `userPriceCoefficient` to correctly determine BPT multiplier
> fix: Use userPriceCoeff

- apps/governance/src/app/pages/Quests/QuestInfo.tsx
- libs/theme/src/lib/theme.ts
- Add manual claim button to Time Multiplier quest to update user timestamp
> Manually claim time multiplier

- apps/governance/src/app/pages/Quests/ClaimButtons.tsx
- apps/governance/src/app/pages/Quests/Meta8Logic.tsx
- apps/governance/src/app/pages/Quests/QuestCard.tsx
- apps/governance/src/app/pages/Quests/QuestInfo.tsx
- Clarify time quest progress
- Show QP required for quests
- Fix cache issue resulting in extra queries
> Quest fixes

- apps/protocol/src/app/pages/Pools/Detail/MintLP.tsx
- libs/quick-maths/src/lib/getDistancePercentage.ts
- Correct LP price passed to func
- Refactor getDistancePercentage (forgot the logic & had to refigure out how it worked)
> fix: Rai penalty pricing

- libs/base/src/lib/components/core/TokenIcon.tsx
- Fix z-index on dropdown as per
> fix: z-index on dropdown

- apps/protocol/src/app/pages/Exchange/SwapLogic.tsx
- apps/protocol/src/app/pages/Save/v2/SaveDeposit.tsx
- Restore FEI to swap & Save deposit
> fix: Restore FEI to swap

- apps/protocol/src/app/index.tsx
- apps/protocol/src/app/pages/Dashboard/Overview.tsx
- apps/protocol/src/app/pages/Dashboard/PoolRow.tsx
- apps/protocol/src/app/pages/Dashboard/Styled.tsx
- apps/protocol/src/app/pages/Dashboard/utils.ts
- apps/protocol/src/app/pages/Pools/cards/PoolDetailCard.tsx
- libs/base/src/lib/components/forms/TransactionInfo.tsx
- Show deprecated pools in Dashboard
- Show USD price on reward hover
- Show DEPRECATED label for deprecated pools & hide APY
> Show deprecated pools in Dashboard

- apps/protocol/src/app/context/SelectedSaveVersionProvider.tsx
- libs/base/src/lib/context/NetworkProvider.tsx
- ethgas.watch is shutting down/unresponsive – switch to MyCrypto API
- Adjust check on v1 savings balance query (handle when not connected)
> Change gas API

- apps/protocol/src/app/pages/Save/v2/SaveRedeem.tsx
- Fixes case where Vault Input > Vault Balance and submit buttons remains clickable
> Expand error cases on SaveRedeem

- apps/governance/src/app/pages/Dials/ActiveDial.tsx
- apps/governance/src/app/pages/Dials/DialMetadataContent.tsx
- apps/governance/src/app/pages/Dials/DialTable.tsx
- apps/governance/src/app/pages/Dials/DialTitle.tsx
Fixes crash where new dials do not have metadata
> Catch undefined dial metadata

- apps/protocol/src/app/hooks/useEstimatedOutput.ts
- apps/protocol/src/app/hooks/useMassetExchangeRate.ts
- apps/protocol/src/app/pages/Save/v2/SaveDeposit.tsx
- apps/protocol/src/app/pages/Save/v2/SaveRedeem.tsx
- libs/base/src/lib/components/forms/AssetExchange.tsx
- libs/base/src/lib/components/forms/ExchangeRate.tsx
- libs/base/src/lib/components/forms/MultiAssetExchange.tsx
- Enables easy offboarding on mainnet
> Mainnet offboard

- apps/protocol/src/app/pages/Save/v2/SaveRedeem.tsx
- Fixes state where wallet is not connected & fetching state persists
> Fix SaveRedeem fetching state

- apps/governance/src/app/pages/Dials/constants.ts
fixed the description and link directly to the relevant page.
> fix: idle dial description

- libs/base/src/lib/components/core/IPFSImg.tsx
see [comment ](https://github.com/mstable/mStable-apps/issues/156#issuecomment-1133189329)
> fix: update ipfs src path to pinata gateway

- apps/governance/src/app/context/DelegateeLists.tsx
- libs/base/src/lib/components/core/IPFSImg.tsx
- new infrura ipfs gateway for delegates
> fix: ipfs gateway

- apps/protocol/src/app/pages/Exchange/SwapLogic.tsx
- libs/base/src/lib/components/forms/AssetExchange.tsx
- libs/base/src/lib/components/forms/AssetSwap.tsx
- libs/base/src/lib/hooks/useCheckPath.ts
#164
- making arrow as Button and add reverse functionality
- only possible it on swap page
> Clicking on the arrow reverses the assets on Swap page

- apps/protocol/src/app/pages/Dashboard/DashboardTable.tsx
> Move deprecated pools to the bottom

- apps/protocol/src/app/pages/Save/v2/SaveDeposit.tsx
- apps/protocol/src/app/pages/Save/v2/SaveRedeem.tsx
> Make the vault as default while depositing and redeeming

- package.json
- yarn.lock
#170 
- Update ethers to latest version(5.6.8)
- Tested the bug mentioned on https://github.com/ethers-io/ethers.js/issues/3017
> fix/bump ethers version to 5.6.8

- package.json
- yarn.lock
> fix/bump ethers version to 5.6.8 (#179)

- apps/protocol/src/app/pages/Save/EthereumSave.tsx
- apps/protocol/src/app/pages/Save/PolygonSave.tsx
- apps/protocol/src/app/pages/Save/v2/OnboardingBanner.tsx
- libs/base/src/lib/components/layout/Footer.tsx
As per this [notion page](https://www.notion.so/mstable/Website-App-Changes-eb101af537db496b8f6cff3a8e561438) 
- update labels on Save page
- add Risk button
- add link to risk page in footer
Any comments welcome
> feat: review risk wording

- libs/base/src/lib/context/AccountProvider.tsx
This PR improves the wallet connection and removes the auto-switch to Eth main net when selected network is unsupported
> fix: remove force network switch

- apps/governance/src/app/pages/Dials/constants.ts
> fix: wrong description

- apps/governance/src/index.html
- apps/protocol/src/index.html
> fix: update font addresses to https

- apps/governance/src/app/pages/Dials/DialSidebar.tsx
- apps/governance/src/app/pages/Dials/DialTable.tsx
- apps/governance/src/app/pages/Dials/DialView.tsx
- apps/governance/src/app/pages/Dials/DistributionBar.tsx
- apps/governance/src/app/pages/Dials/context/EmissionsContext.tsx
- apps/governance/src/app/pages/Dials/context/EpochContext.tsx
- apps/governance/src/app/pages/Dials/types.ts
- libs/artifacts/src/graphql/emissions.tsx
- libs/artifacts/src/graphql/emissions/query.graphql
- libs/artifacts/src/graphql/emissions/schema.graphql
- libs/base/src/lib/components/layout/WalletButton.tsx
- libs/dumb-components/src/lib/Table.tsx
@dimsome I'm not sure to fully understand how the warning message should display, maybe worth to sync 😃
> feat: add disabled marker

- libs/base/src/lib/components/wallet/PendingTransactions.tsx
- libs/base/src/lib/context/WagmiProvider.tsx
- libs/react-utils/src/index.ts
- libs/react-utils/src/lib/iframe.ts
- package.json
- yarn.lock
This PR fixes issues with gnosis safe connector:
- add `SafeWalletConnector` from gnosis sdk
- create rainbowkit custom wallet for handling connector
- update auto-connect feature:
- use `wagmi` autoconnect if not in an iframe (flow for most of the cases, works as it is for now)
- disable `wagmi` autoconncet in iframes, use custom autoconnect hook
> feat: add gnosis wallet connector

- apps/governance/src/app/pages/Stake/StakeMigration.tsx
Adjusting the text to remove the migration multiplier promises.
@toniocodo is there a way to load the APY dynamically?
> chore: adjust wording, remove quest multiplier

- apps/governance/src/app/pages/Quests/Meta8Logic.tsx
Fixes https://github.com/mstable/mStable-apps/issues/216
> Fix hodl time

- apps/governance/src/app/pages/Quests/Meta8Logic.tsx
> Fix timeMultiplier Calculation

- apps/governance/src/app/pages/Quests/Meta8Logic.tsx
> Fix hodl time (#218)

- libs/base/src/lib/components/wallet/StakeValidation.tsx
> Fix modal scroll

- apps/protocol/src/app/context/FraxStakingProvider.tsx
- libs/base/src/lib/context/PricesProvider.tsx
- libs/base/src/lib/context/WagmiProvider.tsx
- libs/base/src/lib/updaters/tokenSubscriptionsUpdater.ts
This PR should fix the empty balance issue on polygon for mUSD/FRAX owners.
> fix: use defaults ws providers

- apps/governance/src/app/pages/Stake/PendingBalances.tsx
> fix: stakes cooldown
